// <auto-generated>
// Rewired Constants
// This list was generated on 9/11/2021 12:30:20 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Horizontal Move Input")]
        public const int Horizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Vertical Move Input")]
        public const int Vertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Jump")]
        public const int Jump = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Punch")]
        public const int Punch = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Kick")]
        public const int Kick = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Special")]
        public const int Special = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Right Stick X")]
        public const int Right_Horizontal = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Right Stick Y")]
        public const int Right_Vertical = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Projectile")]
        public const int Projectile = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Interact")]
        public const int Interact = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Block")]
        public const int Block = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Surf (Hold)")]
        public const int Surf = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Open Inventory")]
        public const int Inventory = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Start Pause")]
        public const int Start = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In-game Actions", friendlyName = "Walk (Hold)")]
        public const int Walk = 15;
        // UI Navigation
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI Navigation Buttons", friendlyName = "Move one tab left in a menu")]
        public const int Tab_Left = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI Navigation Buttons", friendlyName = "Move one tab right in a menu")]
        public const int Tab_Right = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI Navigation Buttons", friendlyName = "UIVertical")]
        public const int UIVertical = 24;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI Navigation Buttons", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 25;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI Navigation Buttons", friendlyName = "UI Submit Input")]
        public const int UISubmit = 22;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI Navigation Buttons", friendlyName = "UI Cancel Input")]
        public const int UICancel = 23;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int UI = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
