//This class is auto-generated, do not modify (use Tools/TagsLayersEnumBuilder)
public abstract class Layers {
	public const string Default = "Default";
	public const string TransparentFX = "TransparentFX";
	public const string IgnoreRaycast = "Ignore Raycast";
	public const string Water = "Water";
	public const string UI = "UI";
	public const string Ground = "Ground";
	public const string Player = "Player";
	public const string Triggers = "Triggers";
	public const string HitHurtboxes = "HitHurtboxes";
	public const string EnemyColliders = "EnemyColliders";
	public const string Pickups = "Pickups";
	public const string Projectiles = "Projectiles";
	public const string Interactables = "Interactables";
	public const string Breakables = "Breakables";
	public const string SpriteMasks = "Sprite Masks";
	public const string Minimap = "Minimap";
	public const string EditorUI = "Editor UI";
	public const string PlayerParticles = "PlayerParticles";

	public const int DefaultMask = 1;
	public const int TransparentFXMask = 1 << 1;
	public const int IgnoreRaycastMask = 1 << 2;
	public const int WaterMask = 1 << 4;
	public const int UIMask = 1 << 5;
	public const int GroundMask = 1 << 8;
	public const int PlayerMask = 1 << 9;
	public const int TriggersMask = 1 << 10;
	public const int HitHurtboxesMask = 1 << 11;
	public const int EnemyCollidersMask = 1 << 12;
	public const int PickupsMask = 1 << 13;
	public const int ProjectilesMask = 1 << 14;
	public const int InteractablesMask = 1 << 15;
	public const int BreakablesMask = 1 << 16;
	public const int SpriteMasksMask = 1 << 17;
	public const int MinimapMask = 1 << 18;
	public const int EditorUIMask = 1 << 19;
	public const int PlayerParticlesMask = 1 << 20;

	public const int DefaultNumber = 0;
	public const int TransparentFXNumber = 1;
	public const int IgnoreRaycastNumber = 2;
	public const int WaterNumber = 4;
	public const int UINumber = 5;
	public const int GroundNumber = 8;
	public const int PlayerNumber = 9;
	public const int TriggersNumber = 10;
	public const int HitHurtboxesNumber = 11;
	public const int EnemyCollidersNumber = 12;
	public const int PickupsNumber = 13;
	public const int ProjectilesNumber = 14;
	public const int InteractablesNumber = 15;
	public const int BreakablesNumber = 16;
	public const int SpriteMasksNumber = 17;
	public const int MinimapNumber = 18;
	public const int EditorUINumber = 19;
	public const int PlayerParticlesNumber = 20;
}
