public enum SubwayStop {
    NIGHT_MARKET,
    WEATHER_STATION_7,
    DEEP_TOWN,
    CERULEAN_COVE,
    TERMINAL,
    MAINTENANCE_TUNNEL,
    FINANCIAL_DISTRICT,
    DOCKS,
    UNDERPASS,
    PARADISE,
    SLUDGE_WASTES,
    EASTERN_TURBINE
}